version: "3.7"

services:
    libraryapi:
        build: ./LibraryAPI/.
        env_file: .env
        ports:
            - "3000:3000"
        volumes:
            - ./LibraryAPI:/app

    postgresdb:
        image: postgres:14
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - postgresdb-data:/var/lib/postgresql/data

volumes:
    postgresdb-data:
