version: "3.7"

services:
    postgresdb:
        image: postgres:14
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - postgresdb-data:/var/lib/postgresql/data

    libraryapi:
        build: ./LibraryAPI/.
        env_file: .env
        ports:
            - "82:3000"
        volumes:
            - ./LibraryAPI:/app

    kwinapi:
        build: ./kwinAPI/.
        env_file: .env
        ports:
            - "82:3000"
        volumes:
            - ./kwinAPI:/app

volumes:
    postgresdb-data:
